export const GET_ALL_BOOK_DATA = "GET_ALL_BOOK_DATA";
export const STORE_PROBLEM_SET_DATA = "STORE_PROBLEM_SET_DATA";
export const INITIALIZE_SECTION_TABLE_DATA = "INITIALIZE_SECTION_TABLE_DATA";
export const STORE_SECTION_CHECKED_ROWS = "STORE_SECTION_CHECKED_ROWS";